version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    on-failure: CONTINUE
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://${DeployBucket}/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://${DeployBucket}/
      - aws cloudfront create-invalidation --distribution-id ${Distribution} --paths /index.html
artifacts:
  files:
    - "**/*"
  base-directory: build
